### PR TITLE
Docker for development

### PR DESCRIPTION
**Pull request by jfharden**
I wanted it to be easier to do development and test changes without needing to experiment on a live website or run on a server remote from my laptop, so I added a Dockerfile, docker-compose files and some necessary dependencies to be able to run in docker locally. I've tried to include a useful README but it's definitely clouded by the fact I use docker all the time in production elsewhere.

I did this for me, but since I have it working I thought you might be interested in it, if not that's fine I don't mind keeping it in my fork and just using it, to that end I've tried to make it as trivial as possible to keep up to date with your upstream, hence why everything in this PR is a new file (merging upstream will be a lot easier by doing this) and I really appreciate being able to keep getting updates from upstream as easily as possible.

Note that the passwords in here are _only_ for local development and only exist in ephemeral containers, they should _never_ be reused anywhere in the real world, and the containers using these passwords should never be exposed to the internet.

Things of note:

1. I've copied the config file and made a dockerised version which reads all the things I thought needed to be configurable for local development from the environment.
2. I've copied the error logging file and changed it to just log everything to stdout (as is usual for docker containers) if WARNING_LOG and ERROR_LOG are set to the string TRUE (since they come from the env, everything is a string)
3. I've had the docker container copy all the _dist.php files to just the non _dist versions so it can run locally, this of course means the terms and conditions, and the styling etc is exactly the default, but since it's only for local development at the moment I thought that would be ok. 

I am planning to extend this further so I can run bitsand in docker in production (on AWS ECS, but the work in the project will be kept to being generic), I'm running about 6 different bitsand instances now and will shortly be adding another one (for the Archers guild), it's a pain to keep them all up to date, and an even bigger pain if I make a manual change to fix something in production getting that into all the instances of it.

### CODE REVIEW

**Comment by jfharden** [comment]
Currently I have 6 PRs open, some of them cause minor merge conflicts.

I have a branch with everything already merged https://github.com/jfharden/bitsand/tree/dev

**Comment by PeteAUK** [comment]
I'm going to have to think about Docker.  It's not something I use nor anybody else has asked for, so need to weigh up the usefulness of it.

**Comment by jfharden** [comment]
I dunno about anyone else but I'm currently running: 

healers, incantors, reality checkpoint, wardens, archers (launching soon), and alchemists sites :)

I'm migrating them all into AWS ECS where they are running as docker containers (load balancer in front of the cluster, it's not based on this branch (this is just for local development, it's this one -> https://github.com/jfharden/bitsand/tree/dockerise-for-production which is pretty specific to me. )

It's not a problem for me if this doesn't get merged of course, I've purposefully made it as easy as possible to keep up to date with upstream in these (no changes in files inside).

I've found it really hard to test any changes with this project and for me personally being able to just run it up locally with docker made it a lot easier (and made it possible to do work on the train with no internet access).

I appreciate there is a fair bit here and not all that many people are familiar with docker day to day so it's no problem for me if you want to leave this and close the PR unmerged.

**Comment by PeteAUK** [comment]
Have merged this prior to the transfer, however not all sites will be running Docker (Dragons certainly isn't) and not all will have access to change environment variables so these need to default to non-Docker with a docker based option

**Pull request merged**
